"""
Utilities package for thesis project.

Provides:
- Travel graph analysis and routing via TravelGraphManager
- JeepneyRoute for defining jeepney services
- Travel graph HTML visualization helpers
- Passenger generation, jeep movement, and tandem simulation tools
- Traffic-biased route generation, scoring, and RL helpers
"""

from .route_generation import (
    BaselineRouteGenerator,
    BaselineRoute,
    JeepneyRouteEnv,
    RouteFitnessResult,
    calculate_route_fitness,
    SystemicFitnessEvaluator,
    SystemicFitnessResult,
    BestWorstRouteCallback,
    RouteTrainingArtifacts,
    RouteTrainingSnapshot,
    build_training_env,
    export_physical_route_html,
    export_training_results_csvs,
    route_nodes_to_latlon,
    train_route_agent,
    build_route_nodes,
    build_route_spectrum_frame,
    compare_route_spectrum_frames,
    plot_correlation_delta,
    plot_correlation_heatmap,
    route_correlation_pairs,
    route_spectrum_correlation,
    summarize_route_spectrum,
)
from .travel_graph import (
    TravelGraphManager,
    JeepneyRoute,
    JeepneySystem,
    JeepneyRouteScrubber,
    TravelGraphVisualizer,
    visualize_travel_graph,
    # Helper functions for graph construction
    make_coord_key,
    resolve_study_area_boundary,
    load_graphs_for_study_area,
    prune_dead_end_nodes,
    node_table_from_graph,
    extract_uncategorized_nodes,
    graph_edges_to_bidirectional_base,
    duplicate_walk_nodes_to_layers,
    build_direct_edges,
    build_interlayer_edges,
    assign_edge_ids,
    edge_frame_to_csv,
    node_frame_to_csv,
    make_edges_gdf,
    make_nodes_gdf,
    add_nodes_to_digraph,
    add_edges_to_digraph,
    compute_v_to_outgoing,
    attach_accessible_nodes,
)

from .passenger_generation import (
    PassengerMap,
    Passenger,
    PassengerState,
    Jeep,
    JeepState,
    SimulationConfig,
    Simulation,
)

__all__ = [
    # Main classes
    "TravelGraphManager",
    "JeepneyRoute",
    "JeepneySystem",
    "JeepneyRouteScrubber",
    "TravelGraphVisualizer",
    "visualize_travel_graph",
    "BaselineRouteGenerator",
    "BaselineRoute",
    "JeepneyRouteEnv",
    "RouteFitnessResult",
    "calculate_route_fitness",
    "SystemicFitnessEvaluator",
    "SystemicFitnessResult",
    "BestWorstRouteCallback",
    "RouteTrainingArtifacts",
    "RouteTrainingSnapshot",
    "build_training_env",
    "export_physical_route_html",
    "export_training_results_csvs",
    "route_nodes_to_latlon",
    "train_route_agent",
    "build_route_nodes",
    "build_route_spectrum_frame",
    "compare_route_spectrum_frames",
    "plot_correlation_delta",
    "plot_correlation_heatmap",
    "route_correlation_pairs",
    "route_spectrum_correlation",
    "summarize_route_spectrum",
    # Graph construction helpers
    "make_coord_key",
    "resolve_study_area_boundary",
    "load_graphs_for_study_area",
    "prune_dead_end_nodes",
    "node_table_from_graph",
    "extract_uncategorized_nodes",
    "graph_edges_to_bidirectional_base",
    "duplicate_walk_nodes_to_layers",
    "build_direct_edges",
    "build_interlayer_edges",
    "assign_edge_ids",
    "edge_frame_to_csv",
    "node_frame_to_csv",
    "make_edges_gdf",
    "make_nodes_gdf",
    "add_nodes_to_digraph",
    "add_edges_to_digraph",
    "compute_v_to_outgoing",
    "attach_accessible_nodes",
    "PassengerMap",
    "Passenger",
    "PassengerState",
    "Jeep",
    "JeepState",
    "SimulationConfig",
    "Simulation",
]
